apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
  labels:
    app: grafana
    component: credentials
type: Opaque
data:
  # admin / admin123 (base64 encoded)
  # Change these credentials in production
  admin-user: YWRtaW4=
  admin-password: YWRtaW4xMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-database-credentials
  namespace: monitoring
  labels:
    app: grafana
    component: database
type: Opaque
data:
  # Database credentials (if used)
  # db-user / dbpass123 (base64 encoded)
  database-user: ZGItdXNlcg==
  database-password: ZGJwYXNzMTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-credentials
  namespace: monitoring
  labels:
    app: grafana
    component: oauth
type: Opaque
data:
  # OAuth credentials for Keycloak integration
  # client-id / client-secret (base64 encoded)
  client-id: Z3JhZmFuYS1jbGllbnQ=
  client-secret: Z3JhZmFuYS1zZWNyZXQtMTIz 