apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    purpose: monitoring-and-observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    name: auth
    purpose: authentication-and-authorization 